server {
    listen 80;

    location / {
        proxy_pass         http://kanboard:80;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        # Kanboard reads this header and auto-logs everyone in as buurtgenoot
        proxy_set_header   X-Remote-User     buurtgenoot;
        proxy_read_timeout 90s;
    }
}
